//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Season
    {
        public Season()
        {
            this.Accessories = new HashSet<Accessory>();
            this.Bottoms = new HashSet<Bottom>();
            this.Shoes = new HashSet<Sho>();
            this.Tops = new HashSet<Top>();
        }
    
        [Display(Name ="Season")]
        public int SeasonID { get; set; }
        [Display(Name ="Season")]
        public string Season1 { get; set; }
    
        public virtual ICollection<Accessory> Accessories { get; set; }
        public virtual ICollection<Bottom> Bottoms { get; set; }
        public virtual ICollection<Sho> Shoes { get; set; }
        public virtual ICollection<Top> Tops { get; set; }
    }
}
