//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Sho
    {
        public Sho()
        {
            this.Outfits = new HashSet<Outfit>();
        }
    
        public int ShoeID { get; set; }
        [Required]
        [Display(Name = "Description of Shoes")]
        public string Name { get; set; }
        [Display(Name = "Enter URL for Photo")]
        public string Photo { get; set; }
        [Display(Name = "Color")]
        public int ColorID { get; set; }
        [Display(Name = "Season")]
        public int SeasonID { get; set; }
        [Display(Name = "Occasion")]
        public int OccasionID { get; set; }

        public virtual Color Color { get; set; }
        public virtual Occasion Occasion { get; set; }
        public virtual ICollection<Outfit> Outfits { get; set; }
        public virtual Season Season { get; set; }
    }
}
